-- Add bio and reveal preference fields to User (idempotent)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio"          TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "revealHandle"  BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "revealBio"     BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "revealGithub"  BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "revealTwitter" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "revealEmail"   BOOLEAN NOT NULL DEFAULT true;
